name: Checkout Demo

on:
  push:

jobs:
  checkout-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Show README
        run: cat README.md